#!/bin/sh

export DOTFILES="$HOME/.dotfiles"

if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then 
  . "$HOME/.nix-profile/etc/profile.d/nix.sh"
  export XDG_DATA_DIRS="$HOME/.nix-profile/share:$XDG_DATA_DIRS"
fi

if ! [ -d "$DOTFILES" ] || [ -z "$BASH_VERSION" ]; then
  echo "dotfiles are not present, nothing to load"
  exit 0
fi

for file in "$DOTFILES/config/bash/env" "$DOTFILES/config/bash/path"; do
  if [ -f "$file" ]; then
    . "$file"
  fi
done

# set key repeat rate [delay per/sec]
xset r rate 200 26

xrdb -merge ~/.Xresources &

setxkbmap pl
