"""Download content CLI commands (registry-driven).

All leaves are generated by :func:`register_download_command` from the
:data:`~notebooklm.cli._download_specs.DOWNLOAD_SPECS` registry. Click renders
the registered commands in ``download --help``, so the public type list cannot
drift from the registry. The
``cinematic-video`` alias is wired afterwards as a thin Click alias
(``download_video.callback`` re-used) because it shares an artifact type
with ``video`` and has no registry presence of its own.

The transport-neutral download core lives in :mod:`notebooklm._app.download`;
:mod:`notebooklm.cli.services.download` is the CLI adapter that injects
resolvers and projects typed results into the historical envelope dict. This
module is the Click boundary and registry-driven command factory.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

import click

from ._download_specs import DOWNLOAD_SPECS, DownloadTypeSpec
from .auth_runtime import resolve_client_factory, run_client_workflow
from .error_handler import exit_with_code, output_error
from .options import _complete_artifacts, alias_command, notebook_option
from .rendering import console, json_output_response
from .services.download import DownloadPlanValidationError, build_download_plan, execute_download

if TYPE_CHECKING:
    from ..client import NotebookLMClient


@click.group()
def download() -> None:
    """Download generated content."""


def _display_download_result(result: dict[str, Any], artifact_type: str) -> None:
    """Render a download envelope to the console for text-mode output.

    Mirrors the legacy renderer byte-for-byte: keys off the *legacy* string
    ``error`` shape for short-circuiting, so the typed-counts envelope
    falls through to the breakdown block.
    """
    if isinstance(result.get("error"), str):
        console.print(f"[red]Error:[/red] {result['error']}")
        if "suggestion" in result:
            console.print(f"[dim]{result['suggestion']}[/dim]")
        return

    if result.get("dry_run"):
        if result["operation"] == "download_all":
            console.print(
                f"[yellow]DRY RUN:[/yellow] Would download {result['count']} "
                f"{artifact_type} files to: {result['output_dir']}"
            )
            console.print("\n[bold]Preview:[/bold]")
            for art in result["artifacts"]:
                console.print(f"  {art['filename']} <- {art['title']}")
        else:
            console.print("[yellow]DRY RUN:[/yellow] Would download:")
            console.print(f"  Artifact: {result['artifact']['title']}")
            console.print(f"  Reason: {result['artifact']['selection_reason']}")
            console.print(f"  Output: {result['output_path']}")
        return

    if result.get("operation") == "download_all":
        items = result.get("artifacts", [])
        downloaded = [r for r in items if r.get("status") == "downloaded"]
        skipped = [r for r in items if r.get("status") == "skipped"]
        failed = [r for r in items if r.get("status") == "failed"]

        console.print(
            f"[bold]Downloaded {len(downloaded)}/{result['total']} "
            f"{artifact_type} files to:[/bold] {result['output_dir']}"
        )

        if downloaded:
            console.print("\n[green]Downloaded:[/green]")
            for r in downloaded:
                console.print(f"  {r['filename']} <- {r['title']}")

        if skipped:
            console.print("\n[yellow]Skipped:[/yellow]")
            for r in skipped:
                console.print(f"  {r['filename']} ({r.get('reason', 'unknown')})")

        if failed:
            console.print("\n[red]Failed:[/red]")
            for r in failed:
                console.print(f"  {r['filename']}: {r.get('error', 'unknown error')}")
    else:
        console.print(
            f"[green]{artifact_type.capitalize()} saved to:[/green] {result['output_path']}"
        )
        console.print(
            f"[dim]Artifact: {result['artifact']['title']} "
            f"({result['artifact']['selection_reason']})[/dim]"
        )


def _run_artifact_download(ctx: click.Context, spec: DownloadTypeSpec, **kwargs: Any) -> None:
    """Click-side adapter: build plan → run executor → render → propagate exit.

    Routes the auth + workflow envelope through ``run_client_workflow`` so
    download commands match the typed-error surface of every other decorator-
    based command. The legacy ``{"error": "<msg>"}`` return shape is preserved
    by returning it from the body and short-circuiting on a string ``error``
    key after the workflow completes.
    """
    json_output = bool(kwargs.get("json_output", False))
    try:
        plan = build_download_plan(spec, kwargs, Path.cwd())
    except DownloadPlanValidationError as exc:
        if json_output:
            output_error(exc.message, exc.code, True, 1)
        raise click.UsageError(  # cli-input-validation: download plan flag/argument validation
            exc.message
        ) from exc

    for warning in plan.warnings:
        click.echo(warning, err=True)

    async def body(client: NotebookLMClient) -> dict[str, Any]:
        return await execute_download(
            plan,
            client,
            json_output=json_output,
            text_progress_sink=console.print,
        )

    result = run_client_workflow(
        ctx,
        command_name=f"download_{spec.name.replace('-', '_')}",
        json_output=json_output,
        body=body,
        client_factory=resolve_client_factory(ctx),
    )

    if json_output:
        json_output_response(result)
    else:
        _display_download_result(result, spec.name)

    # Any top-level "error" key means non-zero exit, regardless of
    # whether it's the legacy string shape or the typed-counts bool flag.
    if "error" in result:
        exit_with_code(1)


def register_download_command(group: click.Group, spec: DownloadTypeSpec) -> click.Command:
    """Build + register the leaf ``download <name>`` Click command from a spec.

    The factory is what makes the 9 leaves fit in a single file under 500
    LOC: every leaf-specific axis (name, kind, extension, default_dir,
    optional ``--format``, help text) lives in the ``DownloadTypeSpec`` row;
    the body is just the shared ``_run_artifact_download`` invocation.

    Returns the registered command so callers (notably the cinematic-video
    alias wiring below) can introspect ``.callback`` / ``.params``.
    """

    @click.pass_context
    def _handler(ctx: click.Context, **kwargs: Any) -> None:
        _run_artifact_download(ctx, spec, **kwargs)

    # Apply the spec's docstring on the handler so Click renders it as the
    # leaf's help text. The literal ``\b`` (form-feed) on its own line tells
    # Click NOT to re-wrap the following paragraph — the original hand-written
    # leaves used the same convention so the ``Examples:`` block stays
    # verbatim with its blank lines and indentation.
    _handler.__doc__ = f"{spec.help_summary}\n\n\b\nExamples:\n{spec.help_examples}\n"

    # Apply standard option decorators (innermost first; Click reads outside-in).
    decorators: list[Any] = []
    # `--format` is the outermost user-facing option when present, so we apply
    # it FIRST in this list (the decorators are applied in reverse below to
    # match the original hand-written order).
    if spec.format_choices:
        decorators.append(
            click.option(
                "--format",
                spec.format_param_name,
                type=click.Choice(list(spec.format_choices)),
                default=spec.format_default,
                help=spec.format_help,
            )
        )

    decorators.extend(
        [
            click.option(
                "--no-clobber",
                is_flag=True,
                # A single download fails if the file exists (matching
                # ``source fulltext --no-clobber``); ``--all`` skips the
                # conflicting files instead of aborting the whole batch.
                help="Don't overwrite existing files (single download fails; --all skips them)",
            ),
            click.option("--force", is_flag=True, help="Overwrite existing files"),
            click.option("--dry-run", is_flag=True, help="Preview without downloading"),
            click.option("--json", "json_output", is_flag=True, help="Output as JSON"),
            click.option(
                "-a",
                "--artifact",
                "artifact_id",
                help="Select by artifact ID",
                shell_complete=_complete_artifacts,
            ),
            click.option("--name", help="Filter by artifact title (fuzzy match)"),
            click.option("--all", "download_all", is_flag=True, help="Download all artifacts"),
            click.option("--earliest", is_flag=True, help="Download earliest"),
            click.option("--latest", is_flag=True, help="Download latest (default behavior)"),
            notebook_option,
            click.argument("output_path", required=False, type=click.Path()),
        ]
    )

    # Build the decorator stack: applied bottom-up so the outermost call to
    # ``group.command()`` sees the final, fully-decorated callable.
    decorated = _handler
    for deco in decorators:
        decorated = deco(decorated)

    return group.command(spec.name)(decorated)


# Register every leaf from the registry. The list ordering is preserved in
# `download --help` output.
for _spec in DOWNLOAD_SPECS:
    register_download_command(download, _spec)


# Cinematic videos share ArtifactTypeCode.VIDEO with standard videos, so
# 'download cinematic-video' is a thin alias re-using download_video's
# params + callback. Kept out of the registry to make the alias contract
# explicit in code.
alias_command(
    download,
    download.commands["video"],
    name="cinematic-video",
    help=(
        "Download cinematic video overview(s) to file.\n\n"
        "Alias for 'download video' — cinematic and standard videos share\n"
        "the same artifact type."
    ),
)
