#!/usr/bin/env bash
set -euo pipefail

parseLog() {
  err="$(jq "$@" 2>&1 > /dev/null)"
  if [ -n $err ]; then
    echo "$@"
  else
    jq "$@"
  fi
}

log() {
  kubectl logs -n $1 -f $2 | parseLog
}

main() {
  FZF_DEFAULT_COMMAND="kubectl get pods --all-namespaces" \
    fzf --info=inline --layout=reverse --header-lines=1 \
      --prompt "$(kubectl config current-context | sed 's/-context$//')> " \
      --header $'╱ Enter (kubectl exec) ╱ CTRL-O (open log in editor) ╱ CTRL-R (reload) ╱\n\n' \
      --bind 'ctrl-/:change-preview-window(80%,border-bottom|hidden|)' \
      --bind 'ctrl-o:execute:${EDITOR:-vim} <(kubectl logs --all-containers --namespace {1} {2}) > /dev/tty' \
      --bind 'ctrl-r:reload:$FZF_DEFAULT_COMMAND' \
      --preview-window up:follow \
      --preview 'kubectl logs --follow --all-containers --tail=10000 --namespace {1} {2}' "$@"
}

log "$@"
