all:
	mkdir -p "$$HOME/.local/share/themes"
	ln -s "$$DOTFILES/config/gtk/Nordic" "$$HOME/.local/share/themes/Nordic"
	gsettings set org.gnome.desktop.interface gtk-theme "Nordic"
	gsettings set org.gnome.desktop.wm.preferences theme "Nordic"
