[general]
destination = "$HOME/.local/state/hyprdynamicmonitors/monitors.lua"
debounce_time_ms = 1500
post_apply_exec = "hyprctl reload"

[profiles.laptop_only]
config_file = "hyprconfigs/laptop-only.lua"
config_file_type = "static"

[[profiles.laptop_only.conditions.required_monitors]]
name = "eDP-1"

[profiles.external_only]
config_file = "hyprconfigs/external-only.lua.tmpl"
config_file_type = "template"

[[profiles.external_only.conditions.required_monitors]]
name = "^(DP|HDMI-A)-.*"
match_name_using_regex = true
monitor_tag = "external"
