[general]
destination = "$HOME/.config/hypr/monitors.conf"
debounce_time_ms = 1000
post_apply_exec = "pkill waybar; waybar & pkill hyprpaper; hyprpaper &"

[tui.colors]
source = "themes/nord.toml"

[fallback_profile]
config_file = "hyprconfigs/laptop.conf"
config_file_type = "static"

[profiles.external_only]
config_file = "hyprconfigs/external.go.tmpl"
config_file_type = "template"

[[profiles.external_only.conditions.required_monitors]]
name = "eDP-1"
monitor_tag = "laptop"

[[profiles.external_only.conditions.required_monitors]]
name = "^(DP|HDMI)-.*"
match_name_using_regex = true
monitor_tag = "external"
