#!/bin/bash

profile=$(aws configure list-profiles | fzf)
export AWS_ACCESS_KEY_ID="$(aws configure get aws_access_key_id --profile="$profile")"
export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key --profile="$profile")
