#!/usr/local/bin/awk -f

/index: [0-9]+/                     { entryStarted=1 }
/state: RUNNING/ && 
  entryStarted                      { isRunning=1 }
/properties:/ && 
  entryStarted && isRunning         { propertiesStarted=1 }
/application\.process\.binary =/ && 
  propertiesStarted                 { 
                                      sub(/.*application\.process\.binary = /, "", $0)
                                      gsub(/"/, "", $0)
                                      program=$0
                                      print program
                                      entryStarted=0
                                      isRunning=0
                                      propertiesStarted=0 
                                    }
