#!/usr/bin/env bash

lockDisabledInputs=(chrome firefox brave zoom vlc)

runningInputs="$(pactl -f json list sink-inputs |
  jq -r '
    .[].properties |
    ."application.process.binary" + " " + ."application.name"')"

for input in "${lockDisabledInputs[@]}"; do
  if [[ "${runningInputs[*]}" =~ $input ]]; then
    echo "$input is running, skipping lock"
    exit 0
  fi
done

i3lock-color
