#!/bin/bash

lockDisabledInputs=( chrome firefox brave zoom vlc )

runningInputs=$(pacmd list-sink-inputs | 
  tail -n +2 |
  "$DOTFILES/scripts/locker-parser")

for input in "${lockDisabledInputs[@]}"; do
  echo "$input"
  if [[ "${runningInputs[*]}" =~ "${input}" ]]; then
    echo "$input is running, skipping lock"
    exit 0
  fi
done

slock
