#!/usr/bin/env bash
# screenshot is a utility for quickly moving the screenshots from ~/Pictures
# to the destination the script is run from and changing their generic name to a
# new one.

set -e

NEW_NAME="$1"

if test -z "$NEW_NAME"; then
  printf "Provide new screenshot name: "
  read NEW_NAME
fi

SCREENSHOT="$(fd --type=file Screenshot ~/Pictures | tail -1)"

cp "$SCREENSHOT" "$NEW_NAME.${SCREENSHOT##*.}"
