set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",wezterm:RGB"
set -as terminal-overrides ",xterm-256color:RGB"
set -g focus-events on
set -g history-limit 50000
set -g set-clipboard on
set -g status off

set -g prefix C-a
unbind C-b
bind C-a send-prefix
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux configuration reloaded"

set -g mouse on
bind -n C-Space copy-mode
unbind -n MouseDrag1Pane
unbind -T copy-mode MouseDrag1Pane

set-window-option -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
