vim.opt.lazyredraw = true                        -- Do not redraw screen in the middle of a macro. Makes them complete faster.
vim.opt.clipboard = { "unnamed", "unnamedplus" } -- Allows neovim to access the system clipboard
vim.opt.scrolloff = 9999                         -- Center the view
vim.opt.number = true                            -- Set numbered lines
vim.opt.relativenumber = true                    -- Set relative numbered lines
vim.opt.hidden = true                            -- Otherwise terminals managed by toggleterm are discarded.
vim.opt.splitbelow = true                        -- Force all horizontal splits to go below current window
vim.opt.splitright = true                        -- Force all vertical splits to go to the right of current window
vim.opt.swapfile = false
vim.opt.pumheight = 10
vim.opt.completeopt = { "menuone", "noselect" }
vim.opt.timeoutlen = 500
vim.opt.undofile = true    -- Peristent undo
vim.opt.updatetime = 300   -- Faster completion (4s default!)
vim.opt.writebackup = false
vim.opt.signcolumn = "yes" -- Always show the sign column, otherwise it would shift the text each time
vim.opt.tabstop = 2        -- The number of spaces a tab is
vim.opt.shiftwidth = 2     -- Number of spaces to use in auto(indent)
vim.opt.softtabstop = 2    -- Just to be clear
vim.opt.expandtab = true   -- Insert tabs as spaces
vim.opt.wrapscan = true    -- Wrap searches
vim.opt.ignorecase = true  -- Ignore search term case...
vim.opt.smartcase = true   -- ... unless term contains an uppercase character
vim.opt.textwidth = 80     -- Hard-wrap text at nth column
vim.opt.wrap = false       -- Don't wrap long lines (good for vsplits, bad otherwise?)
vim.opt.foldmethod = "manual"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
